"""Hello

Revision ID: e187f685e022
Revises: 
Create Date: 2025-10-18 22:03:06.804879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e187f685e022'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Name')
    )
    op.create_table('college',
    sa.Column('Cname', sa.String(length=30), nullable=False),
    sa.Column('Sname', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Sname'], ['student.Name'], ),
    sa.PrimaryKeyConstraint('Cname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college')
    op.drop_table('student')
    # ### end Alembic commands ###
