"""New DB for puppy

Revision ID: 85a4c5ccfa9b
Revises: 
Create Date: 2025-10-18 19:29:01.814840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a4c5ccfa9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('Name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
