"""New Structure

Revision ID: f1785d67546b
Revises: 
Create Date: 2025-10-19 13:23:21.870962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1785d67546b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('Name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('Name')
    )
    op.create_table('college',
    sa.Column('Cname', sa.String(length=30), nullable=False),
    sa.Column('Sname', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Sname'], ['student.Name'], ),
    sa.PrimaryKeyConstraint('Cname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college')
    op.drop_table('student')
    # ### end Alembic commands ###
